name: Docs

on:
  push:
    # branches:
    #   - main

jobs:
    cloudflare:
        runs-on: ubuntu-latest
        steps:
            - run: curl -XPOST "https://api.cloudflare.com/client/v4/accounts/$ACCOUNT_ID/pages/projects/docs/deployments" -H "Authorization: bearer $CLOUDFLARE_API_KEY"