name: Release

on:
  push:
  # release:
  #   types: [released]

jobs:
  pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      # - run: uv build
      # - run: uv publish
  homebrew:
    name: Bump Homebrew formula
    needs: pypi
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      contents: read
    steps:
      # ${{ github.event.release.tag_name }}
      - name: Wait for PyPI release to be available
        run: |
          while true; do
            if curl -s https://pypi.io/packages/source/k/${{ github.event.repository.name }}/${{ github.event.repository.name }}-0.1.0.tar.gz; then
              break
            fi
          done
      - uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: ${{ github.event.repository.name }}
          formula-path: Formula/${{ github.event.repository.name }}.rb
          homebrew-tap: ${{ github.repository_owner }}/homebrew-${{ github.event.repository.name }}
          tag-name: "0.1.0" # "${{ github.event.release.tag_name }}"
          download-url: "https://pypi.io/packages/source/k/${{ github.event.repository.name }}/${{ github.event.repository.name }}-0.1.0.tar.gz"
          commit-message: |
            {{formulaName}} {{version}}
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
