name: Tests

on:
  workflow_dispatch:
  push:
  workflow_call:

# Set default permissions for all jobs
permissions:
  contents: read # Needed to check out code
  checks: write # Needed to report test results
  pull-requests: write # Needed to add comments/annotations to PRs

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Use the official Python action to set up Python because it is faster
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Lint
        run: uv run ruff check

      - name: Run tests
        run: uv run pytest -s --cov=src --cov-report=xml

      - name: Pytest coverage comment
        if: github.event_name == 'pull_request'
        uses: MishaKav/pytest-coverage-comment@v1.1.54
        with:
          pytest-xml-coverage-path: ./coverage.xml
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Use the official Python action to set up Python because it is faster
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - run: uv build --sdist --out-dir test-build
      - run: uv tool run twine check test-build/*.tar.gz
      - run: python -m venv .test-venv && source .test-venv/bin/activate && pip install test-build/*.tar.gz
